### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jf17** [arcana-engine/arcana#1]
C:\Users\Alex\Documents\GitHub\arcana\examples\tanks>cargo build
    Updating crates.io index
    Updating git repository `https://github.com/zakarumych/goods`
    Updating git repository `https://github.com/zakarumych/sierra.git`
error: failed to select a version for the requirement `sierra = "^0.1"`
candidate versions found which didn't match: 0.2.0
location searched: Git repository https://github.com/zakarumych/sierra.git
required by package `arcana v0.1.0 (C:\Users\Alex\Documents\GitHub\arcana)`

**Comment by zakarumych** [comment]
It seems that last master commit predates sierra 0.2 release.
I'll push latest changes.

**Comment by jf17** [comment]
> It seems that last master commit predates sierra 0.2 release.
> I'll push latest changes.

Good. I will wait for the commit.

**Comment by zakarumych** [comment]
Ok, I'll cleaned stuff up and pushed. You can try now

**Comment by jf17** [comment]
> Ok, I'll cleaned stuff up and pushed. You can try now

Build fail. =(

C:\Users\Alex\Documents\GitHub\arcana>cargo build
error: failed to load manifest for workspace member `C:\Users\Alex\Documents\GitHub\arcana\examples\blocks`

Caused by:
  failed to load manifest for dependency `arcana`

Caused by:
  failed to load manifest for dependency `sierra`

Caused by:
  failed to read `C:\Users\Alex\Documents\GitHub\sierra\Cargo.toml`

**Comment by jf17** [comment]
I fixed it with a line of code :
```
# Graphics
sierra = { version = "0.2", features = ["serde-1"], git = "https://github.com/zakarumych/sierra.git" }
```

But after compilation, other errors occurred . =(

```
C:\Users\Alex\Documents\GitHub\arcana\examples\tanks>cargo run
warning: associated function is never used: `find_set`
  --> src\bitset.rs:33:12
   |
33 |     pub fn find_set(&self) -> Option<u32> {
   |            ^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: associated function is never used: `get`
  --> src\bitset.rs:58:12
   |
58 |     pub fn get(&mut self, index: u32) -> bool {
   |            ^^^

warning: associated function is never used: `unset`
  --> src\bitset.rs:90:12
   |
90 |     pub fn unset(&mut self, index: u32) -> bool {
   |            ^^^^^

warning: associated function is never used: `get`
   --> src\bitset.rs:173:12
    |
173 |     pub fn get(&mut self, index: u32) -> bool {
    |            ^^^

warning: associated function is never used: `set`
   --> src\bitset.rs:183:12
    |
183 |     pub fn set(&mut self, index: u32) -> bool {
    |            ^^^

warning: constant is never used: `MAX_ROTATION_SPEED`
   --> src\camera.rs:235:9
    |
235 |         const MAX_ROTATION_SPEED: f32 = 0.1;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: field is never read: `surface`
  --> src\viewport.rs:18:5
   |
18 |     surface: Surface,
   |     ^^^^^^^^^^^^^^^^

warning: unused `Result` that must be used
  --> src\lifespan.rs:40:13
   |
40 |             cx.world.despawn(e);
   |             ^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_must_use)]` on by default
   = note: this `Result` may be an `Err` variant, which should be handled

warning: 8 warnings emitted

    Finished dev [unoptimized + debuginfo] target(s) in 0.47s
     Running `C:\Users\Alex\Documents\GitHub\arcana\target\debug\tanks.exe`
Jul 19 19:00:13.866 ERROR arcana::event: Game startup failed: Not found
error: process didn't exit successfully: `C:\Users\Alex\Documents\GitHub\arcana\target\debug\tanks.exe` (exit code: 1)
```

**Comment by zakarumych** [comment]
Oh, shoot, I've forgot to remove path from sierra dependency.

**Comment by zakarumych** [comment]
`Game startup failed: Not found`.
Right. Right now you need to run examples from `examples` directory. There's config file with paths to assets.

**Comment by zakarumych** [comment]
I guess I can create another config file so it would work from crate root directory as well.

**Comment by jf17** [comment]
> `Game startup failed: Not found`.
> Right. Right now you need to run examples from `examples` directory. There's config file with paths to assets.

It turned out to launch the game. Thanks.

**Comment by zakarumych** [comment]
Yeah. I made it so it can be launched from crate's root now.

**Comment by tree786isback** [comment]
I also getting sierra error (same as OP) with latest commit. Any ideas how to fix it?
