### ISSUE TITLE
-

### ISSUE THREAD

**Issue by frutas-fruit** [arcana-engine/arcana#12]

**Comment by zakarumych** [comment]
Hi!

I've read you original message.
So, right now arcana is not in the good shape where you can just clone repository and build it.
Usually I don't push it broken, but there might be local-path dependencies.

As you can find on https://crates.io, it is not really released.
I was working onto making it release-ready in past few months but got distracted.
I hope to release this summer.

In the meantime you absolutely can try it out, run examples etc.
If it doesn't work, you'd probably need to comment out path dependencies and un-comment remotes.

P.S. If you look for a ready to use engine written in Rust, you can try bevy and macroquad.
