### ISSUE TITLE
You are not an engineer

### ISSUE THREAD

**Issue by ghost** [arcana-engine/arcana#13]
Helo

@zakarumych Please do not call yourself an "Engineer", you are not an engineer. There is no such thing as engineering in software. Engineering is much more serious and complex. Engineering means building real things like turbines and buildings. It is not about sitting behind a keyboard and writing code. Engineering is real, it is not fake and petty like software development.

**Comment by zakarumych** [comment]
I have engineering degree in information and software for computing systems.
With state provided certificate.
With words `engineer` and `software` on it.
Have a nice day.
